#!/usr/bin/env bash
# Verifies that a given Lambda entry point — one that imports lambda/auth,
# directly or transitively — bundles and loads without hitting the
# jose/jwks-rsa ERR_REQUIRE_ESM crash (see lib/auth-lambda-bundling.ts for
# the full background).
#
# WHY THIS SCRIPT EXISTS, AND WHY IT WORKS THE WAY IT DOES
# ----------------------------------------------------------
# Step 2.7 initially tried to verify this fix by hand-replicating CDK's
# esbuild bundling with a plain `esbuild` CLI call + a manually-written
# synthetic package.json. That approach gave a false pass: it used
# `npm install` for the nodeModules step, but the real aws-cdk-lib code
# (aws-lambda-nodejs/lib/package-manager.js) always uses `npm ci` for npm
# projects — which behaves very differently (strict lockfile-consistency
# checking, no silent re-resolution). The hand-rolled version missed a
# real regression that only `npm ci` surfaces. Lesson applied here: don't
# re-implement CDK's bundling logic — drive the real thing.
#
# So this script does NOT reimplement esbuild flags or npm semantics by
# hand. It stands up a throwaway copy of this whole aws-backend/
# directory, wires ONE temporary NodejsFunction into a copy of the real
# stack (reusing the real, already-verified authLambdaCommandHooks from
# lib/auth-lambda-bundling.ts), runs the REAL `cdk synth`, then loads the
# REAL synthesized asset under `node --no-experimental-require-module` —
# which forces the same strict CJS/ESM behavior a runtime without Node's
# newer require(esm) interop would have (this is how Step 2.7 reproduced
# the original, real Lambda cold-start crash locally in the first place).
#
# The original project directory is never modified — everything happens
# in a disposable copy under $TMPDIR, deleted on exit.
#
# USAGE
#   ./scripts/verify-auth-bundle.sh lambda/auth/verify-token.ts
#   ./scripts/verify-auth-bundle.sh                 # defaults to lambda/auth
#
# WHAT THIS DOES verify: the entry point bundles, its nodeModules install
# tree correctly resolves jose to the CJS-compatible pin, and the result
# loads under Node without crashing.
#
# WHAT THIS DOES NOT verify: an actual AWS deployment, a real Firestore
# call, real IAM permissions, or Secrets Manager access — those need a
# real `cdk deploy` against a real AWS account, which this script
# deliberately does not attempt.
set -euo pipefail

ENTRY="${1:-lambda/auth/index.ts}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "Verifying: $ENTRY"
echo "(temporary copy: $WORK_DIR — original project is never modified)"
echo

if [ ! -f "$PROJECT_ROOT/$ENTRY" ]; then
  echo "error: $PROJECT_ROOT/$ENTRY does not exist" >&2
  exit 1
fi

cp -r "$PROJECT_ROOT"/. "$WORK_DIR"/
rm -rf "$WORK_DIR/node_modules" "$WORK_DIR/cdk.out" "$WORK_DIR/dist"

# Wire one temporary, unrouted NodejsFunction into a copy of the real
# stack, using the same options a real future endpoint would need.
cat >> "$WORK_DIR/lib/verify-stack.ts" <<EOF
// Generated by scripts/verify-auth-bundle.sh — not part of the real project.
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as lambdaNodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import * as path from 'path';
import { authLambdaCommandHooks } from './auth-lambda-bundling';

// Explicit outdir: App() only defaults to ./cdk.out when invoked through
// the 'cdk' CLI, which sets the CDK_OUTDIR env var. Running via ts-node
// directly (as this script does) means that's never set.
const app = new cdk.App({ outdir: 'cdk.out' });
const stack = new cdk.Stack(app, 'VerifyAuthBundleStack');
new lambdaNodejs.NodejsFunction(stack, 'VerifyFn', {
  entry: path.join(__dirname, '..', '${ENTRY}'),
  handler: 'handler',
  runtime: lambda.Runtime.NODEJS_22_X,
  bundling: {
    nodeModules: ['firebase-admin'],
    forceDockerBundling: false,
    minify: true,
    sourceMap: true,
    target: 'node22',
    commandHooks: authLambdaCommandHooks,
  },
});
app.synth();
EOF

cd "$WORK_DIR"
echo "Installing dependencies (npm ci, real registry)..."
npm ci --no-audit --no-fund --silent

echo "Running real cdk synth..."
npx ts-node --prefer-ts-exts lib/verify-stack.ts >/dev/null

ASSET_DIR="$(find cdk.out -maxdepth 1 -iname 'asset.*' -newer lib/verify-stack.ts | head -1)"
if [ -z "$ASSET_DIR" ]; then
  echo "FAIL: could not locate the synthesized asset." >&2
  exit 1
fi

echo "Bundle produced at: $ASSET_DIR"
echo "Loading it under node --no-experimental-require-module (strict CJS/ESM, no leniency)..."
echo

if node --no-experimental-require-module -e "require('$(pwd)/$ASSET_DIR/index.js'); console.log('module graph loaded cleanly');"; then
  echo
  echo "PASS: $ENTRY bundles and loads without the jose/jwks-rsa ERR_REQUIRE_ESM crash."
  echo "Note: this confirms the module loads. It does not call any AWS/Firebase API —"
  echo "that still needs a real 'cdk deploy' to a real account to confirm end-to-end."
else
  echo
  echo "FAIL: $ENTRY still crashes at load time. Do not deploy until this passes." >&2
  exit 1
fi
